name: Terrafrom deploy
on:
  push:
    branches: [main]

jobs:
  terrafrom:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./main/eu-west-2/staging
    steps:
      - name: Chechout code
        uses: actions/checkout@v4

      - name: Set up terraform on runner
        uses: hashicorp/setup-terraform@v2

      - name: Initialize terraform
        run: terrafrom init

      - name: Terraform format
        run: |
          ter fmt
          ter fmt -recursive ../../variables.tf
          ter fmt -recursive ../../../modules
